# Generated by Django 6.0 on 2025-12-18 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shop_address_shop_email_shop_phone_shop_website_and_more'),
        ('users', '0005_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='shops.branch'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='shops.shop'),
        ),
    ]
