# Generated by Django 6.0 on 2025-12-26 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_shop_public_visibility_shop_slug'),
        ('users', '0007_customuser_commission_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='description',
        ),
        migrations.AddField(
            model_name='role',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='shops.shop'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(help_text='e.g. Manager, Cashier', max_length=50),
        ),
    ]
