# Generated by Django 6.0 on 2025-12-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='eDuka SaaS', max_length=100)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('allow_registration', models.BooleanField(default=True)),
                ('default_currency', models.CharField(default='TZS', max_length=10)),
                ('support_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('trial_days', models.IntegerField(default=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
