# Generated by Django 6.0 on 2025-12-15 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='si_unit',
            field=models.CharField(blank=True, help_text='e.g. Kilo, Dozen, Pcs', max_length=50, null=True),
        ),
    ]
