# Generated by Django 6.0 on 2025-12-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='billing_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='next_billing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='plan',
            field=models.CharField(choices=[('TRIAL', 'Trial'), ('DUKA', 'Duka'), ('ENTERPRISE', 'Enterprise')], default='TRIAL', max_length=20),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
