# Generated by Django 6.0 on 2025-12-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='billing_cycle',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='price',
        ),
        migrations.AddField(
            model_name='shopsubscription',
            name='billing_cycle',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('BIANNUALLY', 'Biannually'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=20),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='price_biannually',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='price_daily',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='price_monthly',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='price_quarterly',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='price_weekly',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='price_yearly',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
