# Generated by Django 6.0 on 2025-12-21 08:28

from django.db import migrations

def update_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model('subscriptions', 'SubscriptionPlan')
    
    plans = [
        {
            'name': 'Lite',
            'slug': 'lite',
            'price_daily': 1000,
            'price_weekly': 0,
            'price_monthly': 0,
            'price_quarterly': 0,
            'price_biannually': 0,
            'price_yearly': 0,
            'features': {"shops": 1, "users": 1, "products": 50},
            'max_shops': 1, 'max_users': 1, 'max_products': 50
        },
        {
            'name': 'Basic',
            'slug': 'basic',
            'price_daily': 0,
            'price_weekly': 5000,
            'price_monthly': 0,
            'price_quarterly': 0,
            'price_biannually': 0,
            'price_yearly': 0,
            'features': {"shops": 1, "users": 2, "products": 200},
            'max_shops': 1, 'max_users': 2, 'max_products': 200
        },
        {
            'name': 'Standard',
            'slug': 'standard',
            'price_daily': 0,
            'price_weekly': 0,
            'price_monthly': 15000,
            'price_quarterly': 0,
            'price_biannually': 0,
            'price_yearly': 0,
            'features': {"shops": 2, "users": 5, "products": 1000},
            'max_shops': 2, 'max_users': 5, 'max_products': 1000
        },
        {
            'name': 'Plus',
            'slug': 'plus',
            'price_daily': 0,
            'price_weekly': 0,
            'price_monthly': 0,
            'price_quarterly': 38000,
            'price_biannually': 0,
            'price_yearly': 0,
            'features': {"shops": 3, "users": 10, "products": 5000},
            'max_shops': 3, 'max_users': 10, 'max_products': 5000
        },
        {
            'name': '+Plus',
            'slug': 'plus-plus',
            'price_daily': 0,
            'price_weekly': 0,
            'price_monthly': 0,
            'price_quarterly': 0,
            'price_biannually': 68000,
            'price_yearly': 0,
            'features': {"shops": 5, "users": 20, "products": 10000},
            'max_shops': 5, 'max_users': 20, 'max_products': 10000
        },
        {
            'name': 'Premium',
            'slug': 'premium',
            'price_daily': 0,
            'price_weekly': 0,
            'price_monthly': 0,
            'price_quarterly': 0,
            'price_biannually': 0,
            'price_yearly': 115000,
            'features': {"shops": 10, "users": 50, "products": 100000},
            'max_shops': 10, 'max_users': 50, 'max_products': 100000
        },
    ]

    for plan_data in plans:
        SubscriptionPlan.objects.update_or_create(
            slug=plan_data['slug'],
            defaults=plan_data
        )

class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_remove_subscriptionplan_billing_cycle_and_more'),
    ]

    operations = [
        migrations.RunPython(update_plans),
    ]
